atlas_environment = "hub"
aws_account_id = "284224159432"
bucket_name = "subpoena-data"
source_bucket_name = "s3.grindr.com"
ec2_instance_type = "m4.large"
project_name = "psyclone"
project_owner = "isre"
