---
 - name: install python development packages
   package: name={{ item }} state=present
   with_items:
     - python-dev
     - libssl-dev
     - python-pip

 - name: install aws cli
   pip: name=awscli state=present

 - name: install boto
   pip: name=boto state=present

 - name: install aws bash completions
   file:
     src: /usr/local/bin/aws_bash_completer
     dest: /etc/bash_completion.d/aws
     owner: root
     group: root
     mode: 0755
     state: link

 - name: create directory for .aws
   file:
     path: /home/vagrant/.aws
     state: directory
     owner: vagrant
     group: vagrant
     mode: 0700


 - name: aws region config
   copy:
     src: aws_config
     dest: /home/vagrant/.aws/config
     owner: vagrant
     group: vagrant
     mode: 0600

 - name: create go directory
   file: path=/opt/go-{{ go_version }} state=directory

 - name: install go
   unarchive:
     copy: no
     src: https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz
     dest: /opt/go-{{ go_version }}
     creates: /opt/go-{{ go_version }}/go/README.md

 - name: create go symlinks
   file: src=/opt/go-{{ go_version }}/go/bin/{{ item }} dest=/usr/local/bin/{{ item }} state=link
   with_items:
     - go
     - gofmt
     - godoc

 - name: create goroot symlink
   file: src=/opt/go-{{ go_version }}/go/ dest=/usr/local/go state=link

 - name: allow ssh env aws
   lineinfile: dest=/etc/ssh/sshd_config
               regexp="^AcceptEnv LANG LC_\*"
               line="AcceptEnv LANG LC_* AWS_*"
   notify: restart ssh

 - name: synchronize clock
   cron: name=ntp weekday=* minute="*/10" hour=* user=root job="sntp -s pool.ntp.org"

 - name: configure smart prompt
   blockinfile:
     state: present
     dest: /home/vagrant/.bashrc
     owner: vagrant
     group: vagrant
     block: "{{ lookup('file', 'bash-prompt-aws.sh') }}"

 - name: ssh config
   copy:
     src: ssh_config
     dest: /home/vagrant/.ssh/config
     owner: vagrant
     group: vagrant
     mode: 0600
